#! /usr/bin/env python3
"""
This is the core of the AutoClone program. It is the main interface that the
user will interact with. This script handles commands and is able to manipulate
the acdaemon.py daemon that drives the AutoClone transfer process. This script
also provides data about the program.

Author: tgsachse (Tiger Sachse)
Initial Release: 7/13/2017
Current Release: 7/13/2017
Version: 0.01
License: GNU GPLv3
"""
import os
import sys
#import signal

command = sys.argv[1]
valid = ['start', 'stop',
         'enable', 'disable',
         'setup', 'status',
         'version']

if command in valid:
    if command == 'start':
        os.system('systemctl start autoclone.service')
    
    elif command == 'stop':
        os.system('systemctl stop autoclone.service')

    elif command == 'enable':
        os.system('systemctl enable autoclone.service')

    elif command == 'disable':
        os.system('systemctl disable autoclone.service')

    elif command == 'setup':
        pass
    
    elif command == 'status':
        pass
    
    
    
    
    
else:
    print("Invalid command.")
