#! /usr/bin/env python3
"""
This is the core of the viento program. It is the main interface that the
user will interact with. This script handles commands and is able to manipulate
the viento_daemon.py script that is behind the viento transfer process. This
script also provides information about the program.

Author: tgsachse (Tiger Sachse)
Initial Release: 7/13/2017
Current Release: 8/01/2017
Version 0.5.0-beta
License: GNU GPLv3
"""
import os
import sys
import signal
from viento import viento_utils

### FUNCTIONS ###
def main():
    """
    Allows the user to control the viento daemon and setup utility. The valid
    list of commands will likely be expanded.
    """
    try:
        command = sys.argv[1]
    except IndexError:
        print("No command entered. " + 
              "Enter 'viento help' for a list of commands.")
        quit()

    valid = ['start', 'stop',
             'enable', 'disable',
             'setup', 'status',
             'version', 'force',
             'stats','help']

    if command in valid:
        if command == 'setup':
            from viento import viento_setup #is this heresy? ;)
            viento_setup.main()

        elif command == 'version':
            os.system('clear')
            print("Viento Cloud Management Utility\n\n" +
                  "Version: v0.5.0-beta\n" +
                  "Author: tgsachse (Tiger Sachse)\n" +
                  "Intitial Release: 7/13/2017\n" +
                  "Current Release: 8/01/2017\n" +
                  "License: GNU GPLv3")

        elif command == 'help':
            os.system('clear')
            print("Welcome to Viento. Here's a list of commands:\n" +
                  "start    stop    enable\n" +
                  "disable  setup   status\n" +
                  "version  force   help\n" +
                  "stats")
        
        if viento_utils.setup_check() == False:
            """
            Checks for a drafts.json file and a service file.
            """
            print("You must have a service file for" +
                  " Viento to function properly.")
            print("If you wish to edit the location of the service file, " + 
                  "please edit the f_service variable in the " + 
                  "viento_utils.py source file located in your python3 " + 
                  "site-packages folder.")
            quit()
            
        elif command == 'start':
            os.system('systemctl --user start viento.service')
            print("Viento service started.")
            viento_utils.log('inst_start')

        elif command == 'stop':
            os.system('systemctl --user stop viento.service')
            print("Viento service stopped.")
            viento_utils.log('inst_stop')
            try:
                os.remove(viento_utils.f_pid)
            except FileNotFoundError:
                pass

        elif command == 'enable':
            os.system('systemctl --user enable viento.service')
            print("Viento service enabled at login on next boot")
            print("Run 'viento start' to start the service right now.")
            viento_utils.log('inst_enable')

        elif command == 'disable':
            os.system('systemctl --user disable viento.service')
            print("Viento service disabled at login on next boot")
            print("Run 'viento stop' to stop the service right now.")
            viento_utils.log('inst_disable')

        elif command == 'status':
            os.system('systemctl --user status viento.service')

        elif command == 'force':
            """
            Used to force the daemon to activate a draft regardless of
            intervals. First this command asks the user which draft to force
            using the command_list() and draft_select() functions in
            viento_utils. Then the resulting draft ID is written to a temporary
            file (f_force) and the pid of the daemon is read from the f_pid
            file. Finally os.kill() is called to send a signal to the daemon to
            read the temporary file and activate the draft.
            """
            from viento import viento_setup
            os.system('clear')
            viento_setup.command_list(show_header=False)
            with open(viento_utils.f_force, 'w') as f:
                force_id = viento_setup.draft_select()[0]
                f.write(force_id)

            try:
                with open(viento_utils.f_pid, 'r') as f:
                    pid = int(f.read())
                os.kill(pid, signal.SIGUSR2)

            except FileNotFoundError:
                print("Viento is not currently running or the pid.dat " +
                      "file has been deleted.")

        elif command == 'stats':
            """
            Runs the statistics_print() command in viento_utils to display the
            current statistics on the screen.
            """
            viento_utils.statistics_print()

    else:
        print("Invalid command.")

### BEGIN PROGRAM ###
if __name__ == '__main__':
    main()
